source 'https://rubygems.org'


gem 'rails', '~> 5.0.2'

gem 'spring', :group => :development

gem 'listen', :group => :development
gem 'bcrypt'
gem 'pg'
gem 'rack-cors'
gem 'faker', '~> 1.6.3'



# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
